// <auto-generated />
namespace ECommerce_Shop_Online_MVC_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initialize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialize));
        
        string IMigrationMetadata.Id
        {
            get { return "202009120735565_initialize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
